Repository aws/eks-distro-prow-jobs, pull requests merged in 2021-10, with the labels that each got.

#227 kubernetes: local registry for go-runner + proxy base images
  jobs/aws/eks-distro/kubernetes-1-18-presubmits.yaml
  jobs/aws/eks-distro/kubernetes-1-19-presubmits.yaml
  jobs/aws/eks-distro/kubernetes-1-20-presubmits.yaml
  jobs/aws/eks-distro/kubernetes-1-21-presubmits.yaml
Labels: lgtm, approved, size/L

#228 kubernetes: push to local reg
  jobs/aws/eks-distro/kubernetes-1-18-presubmits.yaml
  jobs/aws/eks-distro/kubernetes-1-19-presubmits.yaml
  jobs/aws/eks-distro/kubernetes-1-20-presubmits.yaml
  jobs/aws/eks-distro/kubernetes-1-21-presubmits.yaml
Labels: lgtm, approved, size/S

#230 kubernetes: clean after build release project
  jobs/aws/eks-distro/kubernetes-1-18-presubmits.yaml
  jobs/aws/eks-distro/kubernetes-1-19-presubmits.yaml
  jobs/aws/eks-distro/kubernetes-1-20-presubmits.yaml
  jobs/aws/eks-distro/kubernetes-1-21-presubmits.yaml
Labels: lgtm, approved, size/XS

#229 trigger on common script changes
  jobs/aws/eks-distro/aws-iam-authenticator-1-18-presubmits.yaml
  jobs/aws/eks-distro/aws-iam-authenticator-1-19-presubmits.yaml
  jobs/aws/eks-distro/aws-iam-authenticator-1-20-presubmits.yaml
  jobs/aws/eks-distro/aws-iam-authenticator-1-21-presubmits.yaml
  jobs/aws/eks-distro/build-1-18-minimal-postsubmits.yaml
  jobs/aws/eks-distro/build-1-18-postsubmits.yaml
  jobs/aws/eks-distro/build-1-19-minimal-postsubmits.yaml
  jobs/aws/eks-distro/build-1-19-postsubmits.yaml
  jobs/aws/eks-distro/build-1-20-minimal-postsubmits.yaml
  jobs/aws/eks-distro/build-1-20-postsubmits.yaml
  jobs/aws/eks-distro/build-1-21-minimal-postsubmits.yaml
  jobs/aws/eks-distro/build-1-21-postsubmits.yaml
  jobs/aws/eks-distro/cni-presubmits.yaml
  jobs/aws/eks-distro/coredns-1-18-presubmits.yaml
  jobs/aws/eks-distro/coredns-1-19-presubmits.yaml
  jobs/aws/eks-distro/coredns-1-20-presubmits.yaml
  jobs/aws/eks-distro/coredns-1-21-presubmits.yaml
  jobs/aws/eks-distro/dev-release-1-18-postsubmits.yaml
  jobs/aws/eks-distro/dev-release-1-19-postsubmits.yaml
  jobs/aws/eks-distro/dev-release-1-20-postsubmits.yaml
  jobs/aws/eks-distro/dev-release-1-21-postsubmits.yaml
  jobs/aws/eks-distro/etcd-1-18-presubmits.yaml
  jobs/aws/eks-distro/etcd-1-19-presubmits.yaml
  jobs/aws/eks-distro/etcd-1-20-presubmits.yaml
  jobs/aws/eks-distro/etcd-1-21-presubmits.yaml
  jobs/aws/eks-distro/external-attacher-presubmits.yaml
  jobs/aws/eks-distro/external-provisioner-presubmits.yaml
  jobs/aws/eks-distro/external-resizer-presubmits.yaml
  jobs/aws/eks-distro/external-snapshotter-presubmits.yaml
  jobs/aws/eks-distro/kubernetes-1-18-presubmits.yaml
  jobs/aws/eks-distro/kubernetes-1-18-release-presubmits.yaml
  jobs/aws/eks-distro/kubernetes-1-19-presubmits.yaml
  jobs/aws/eks-distro/kubernetes-1-19-release-presubmits.yaml
  jobs/aws/eks-distro/kubernetes-1-20-presubmits.yaml
  jobs/aws/eks-distro/kubernetes-1-20-release-presubmits.yaml
  jobs/aws/eks-distro/kubernetes-1-21-presubmits.yaml
  jobs/aws/eks-distro/kubernetes-1-21-release-presubmits.yaml
  jobs/aws/eks-distro/livenessprobe-presubmits.yaml
  jobs/aws/eks-distro/metrics-server-1-18-presubmits.yaml
  jobs/aws/eks-distro/metrics-server-1-19-presubmits.yaml
  jobs/aws/eks-distro/metrics-server-1-20-presubmits.yaml
  jobs/aws/eks-distro/metrics-server-1-21-presubmits.yaml
  jobs/aws/eks-distro/node-driver-registrar-presubmits.yaml
  jobs/aws/eks-distro/prod-release-1-18-postsubmits.yaml
  jobs/aws/eks-distro/prod-release-1-19-postsubmits.yaml
  jobs/aws/eks-distro/prod-release-1-20-postsubmits.yaml
  jobs/aws/eks-distro/prod-release-1-21-postsubmits.yaml
Labels: lgtm, approved, size/L

#231 metrics-server 1.19: fix formatting
  jobs/aws/eks-distro/metrics-server-1-19-presubmits.yaml
Labels: lgtm, approved, size/XS

#232 Fix indentation on prod release postsubmit
  jobs/aws/eks-distro/prod-release-1-20-postsubmits.yaml
Labels: lgtm, approved, size/XS

#233 kubernetes-presubmit: only push release images to local registry
  jobs/aws/eks-distro/kubernetes-1-18-presubmits.yaml
  jobs/aws/eks-distro/kubernetes-1-19-presubmits.yaml
  jobs/aws/eks-distro/kubernetes-1-20-presubmits.yaml
  jobs/aws/eks-distro/kubernetes-1-21-presubmits.yaml
Labels: lgtm, approved, size/S
