Repository aws/eks-distro-prow-jobs, pull requests merged in 2022-12, with the labels that each got.

#420 Run the base nodejs build before compiler in presubmit
  jobs/aws/eks-distro-build-tooling/eks-distro-base-presubmits-nodejs-16-2022.yaml
  jobs/aws/eks-distro-build-tooling/eks-distro-base-presubmits-nodejs-16.yaml
  templater/jobs/presubmit/eks-distro-build-tooling/eks-distro-base-presubmits-nodejs-16-2022.yaml
  templater/jobs/presubmit/eks-distro-build-tooling/eks-distro-base-presubmits-nodejs-16.yaml
Labels: lgtm, approved, size/XS

#421 Add image build to golang jobs
  jobs/aws/eks-distro-build-tooling/golang-1-15-ARM64-PROD-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1-15-ARM64-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1-15-PROD-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1-15-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1-15-presubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1-16-ARM64-PROD-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1-16-ARM64-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1-16-PROD-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1-16-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1-16-presubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1-17-ARM64-PROD-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1-17-ARM64-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1-17-PROD-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1-17-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1-17-presubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1-18-ARM64-PROD-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1-18-ARM64-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1-18-PROD-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1-18-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1-18-presubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1-19-ARM64-PROD-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1-19-ARM64-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1-19-PROD-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1-19-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1-19-presubmits.yaml
  templater/jobs/postsubmit/eks-distro-build-tooling/golang-1-X-ARM64-PROD-postsubmits.yaml
  templater/jobs/postsubmit/eks-distro-build-tooling/golang-1-X-ARM64-postsubmits.yaml
  templater/jobs/postsubmit/eks-distro-build-tooling/golang-1-X-PROD-postsubmits.yaml
  templater/jobs/postsubmit/eks-distro-build-tooling/golang-1-X-postsubmits.yaml
  templater/jobs/presubmit/eks-distro-build-tooling/golang-1-X-presubmits.yaml
Labels: lgtm, approved, size/XL

#422 update prod post-submits to not duplicate AWS_REGION env var for golang
  jobs/aws/eks-distro-build-tooling/golang-1-15-ARM64-PROD-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1-15-PROD-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1-16-ARM64-PROD-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1-16-PROD-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1-17-ARM64-PROD-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1-17-PROD-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1-18-ARM64-PROD-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1-18-PROD-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1-19-ARM64-PROD-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1-19-PROD-postsubmits.yaml
  templater/jobs/postsubmit/eks-distro-build-tooling/golang-1-X-ARM64-PROD-postsubmits.yaml
  templater/jobs/postsubmit/eks-distro-build-tooling/golang-1-X-PROD-postsubmits.yaml
Labels: lgtm, approved, size/S

#423 use standard builder-base image as the base for golang prow jobs
  jobs/aws/eks-distro-build-tooling/golang-1-15-presubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1-16-presubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1-17-presubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1-18-presubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1-19-presubmits.yaml
  templater/jobs/presubmit/eks-distro-build-tooling/golang-1-X-presubmits.yaml
Labels: lgtm, approved, size/S

#425 remove make install from presubmit for golang
  jobs/aws/eks-distro-build-tooling/golang-1-15-presubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1-16-presubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1-17-presubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1-18-presubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1-19-presubmits.yaml
  templater/jobs/presubmit/eks-distro-build-tooling/golang-1-X-presubmits.yaml
Labels: lgtm, approved, size/S

#427 Adds aws CCM presubmits
  jobs/aws/eks-distro/aws-cloud-controller-manager-1-21-presubmits.yaml
  jobs/aws/eks-distro/aws-cloud-controller-manager-1-22-presubmits.yaml
  jobs/aws/eks-distro/aws-cloud-controller-manager-1-23-presubmits.yaml
  jobs/aws/eks-distro/aws-cloud-controller-manager-1-24-presubmits.yaml
  templater/jobs/presubmit/eks-distro/aws-cloud-controller-manager-1-X-presubmits.yaml
Labels: lgtm, approved, size/L

#428 Adds local registry to ccm presubmit
  jobs/aws/eks-distro/aws-cloud-controller-manager-1-21-presubmits.yaml
  jobs/aws/eks-distro/aws-cloud-controller-manager-1-22-presubmits.yaml
  jobs/aws/eks-distro/aws-cloud-controller-manager-1-23-presubmits.yaml
  jobs/aws/eks-distro/aws-cloud-controller-manager-1-24-presubmits.yaml
  templater/jobs/presubmit/eks-distro/aws-cloud-controller-manager-1-X-presubmits.yaml
Labels: lgtm, approved, size/M

#431 Cleans after images for sidecar windows images
  jobs/aws/eks-distro/livenessprobe-1-21-presubmits.yaml
  jobs/aws/eks-distro/livenessprobe-1-22-presubmits.yaml
  jobs/aws/eks-distro/livenessprobe-1-23-presubmits.yaml
  jobs/aws/eks-distro/livenessprobe-1-24-presubmits.yaml
  jobs/aws/eks-distro/node-driver-registrar-1-21-presubmits.yaml
  jobs/aws/eks-distro/node-driver-registrar-1-22-presubmits.yaml
  jobs/aws/eks-distro/node-driver-registrar-1-23-presubmits.yaml
  jobs/aws/eks-distro/node-driver-registrar-1-24-presubmits.yaml
  templater/jobs/presubmit/eks-distro/livenessprobe-1-X-presubmits.yaml
  templater/jobs/presubmit/eks-distro/node-driver-registrar-1-X-presubmits.yaml
Labels: lgtm, approved, size/S

#432 use builder-base for golang post-submits
  jobs/aws/eks-distro-build-tooling/golang-1-15-ARM64-PROD-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1-15-ARM64-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1-15-PROD-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1-15-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1-16-ARM64-PROD-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1-16-ARM64-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1-16-PROD-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1-16-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1-17-ARM64-PROD-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1-17-ARM64-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1-17-PROD-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1-17-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1-18-ARM64-PROD-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1-18-ARM64-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1-18-PROD-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1-18-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1-19-ARM64-PROD-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1-19-ARM64-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1-19-PROD-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1-19-postsubmits.yaml
  templater/jobs/postsubmit/eks-distro-build-tooling/golang-1-X-ARM64-PROD-postsubmits.yaml
  templater/jobs/postsubmit/eks-distro-build-tooling/golang-1-X-ARM64-postsubmits.yaml
  templater/jobs/postsubmit/eks-distro-build-tooling/golang-1-X-PROD-postsubmits.yaml
  templater/jobs/postsubmit/eks-distro-build-tooling/golang-1-X-postsubmits.yaml
Labels: lgtm, approved, size/M

#433 Decreases request for builder-base bulds
  jobs/aws/eks-distro-build-tooling/builder-base-postsubmits-2022.yaml
  jobs/aws/eks-distro-build-tooling/builder-base-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/builder-base-presubmits-2022.yaml
  jobs/aws/eks-distro-build-tooling/builder-base-presubmits.yaml
  templater/jobs/postsubmit/eks-distro-build-tooling/builder-base-postsubmits-2022.yaml
  templater/jobs/postsubmit/eks-distro-build-tooling/builder-base-postsubmits.yaml
  templater/jobs/presubmit/eks-distro-build-tooling/builder-base-presubmits-2022.yaml
  templater/jobs/presubmit/eks-distro-build-tooling/builder-base-presubmits.yaml
Labels: lgtm, approved, size/M

#434 Run eks go post on make change
  jobs/aws/eks-distro-build-tooling/golang-1-15-ARM64-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1-15-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1-16-ARM64-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1-16-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1-17-ARM64-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1-17-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1-18-ARM64-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1-18-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1-19-ARM64-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1-19-postsubmits.yaml
  templater/jobs/postsubmit/eks-distro-build-tooling/golang-1-X-ARM64-postsubmits.yaml
  templater/jobs/postsubmit/eks-distro-build-tooling/golang-1-X-postsubmits.yaml
Labels: lgtm, approved, size/S

#436 Fixes disk-usage label missing from prow jobs
  jobs/aws/eks-distro-build-tooling/aws-for-fluent-bit-helm-chart-presubmits.yaml
  jobs/aws/eks-distro-build-tooling/eks-distro-base-make-tests.yaml
  jobs/aws/eks-distro-build-tooling/eks-distro-release-presubmits.yaml
  jobs/aws/eks-distro-build-tooling/grafana-helm-chart-presubmits.yaml
  jobs/aws/eks-distro-build-tooling/helm-chart-presubmits.yaml
  jobs/aws/eks-distro-build-tooling/kops-presubmits.yaml
  jobs/aws/eks-distro-build-tooling/prometheus-helm-chart-presubmits.yaml
  jobs/aws/eks-distro-prow-jobs/prowjobs-lint-presubmits.yaml
  jobs/aws/eks-distro/cni-1-21-presubmits.yaml
  jobs/aws/eks-distro/cni-1-22-presubmits.yaml
  jobs/aws/eks-distro/cni-1-23-presubmits.yaml
  jobs/aws/eks-distro/cni-1-24-presubmits.yaml
  jobs/aws/eks-distro/eks-distro-docs-presubmits.yaml
  jobs/aws/eks-distro/kubernetes-1-21-test-presubmits.yaml
  jobs/aws/eks-distro/kubernetes-1-22-test-presubmits.yaml
  jobs/aws/eks-distro/kubernetes-1-23-test-presubmits.yaml
  jobs/aws/eks-distro/kubernetes-1-24-test-presubmits.yaml
  jobs/aws/eks-distro/main-presubmits.yaml
  templater/templates/presubmits.yaml
Labels: lgtm, approved, size/M

#438 Fixes status/done handling for non-image builds
  jobs/aws/eks-distro-build-tooling/aws-for-fluent-bit-helm-chart-presubmits.yaml
  jobs/aws/eks-distro-build-tooling/eks-distro-base-make-tests.yaml
  jobs/aws/eks-distro-build-tooling/eks-distro-release-presubmits.yaml
  jobs/aws/eks-distro-build-tooling/grafana-helm-chart-presubmits.yaml
  jobs/aws/eks-distro-build-tooling/helm-chart-presubmits.yaml
  jobs/aws/eks-distro-build-tooling/kops-presubmits.yaml
  jobs/aws/eks-distro-build-tooling/prometheus-helm-chart-presubmits.yaml
  jobs/aws/eks-distro-prow-jobs/prowjobs-lint-presubmits.yaml
  jobs/aws/eks-distro/cni-1-21-presubmits.yaml
  jobs/aws/eks-distro/cni-1-22-presubmits.yaml
  jobs/aws/eks-distro/cni-1-23-presubmits.yaml
  jobs/aws/eks-distro/cni-1-24-presubmits.yaml
  jobs/aws/eks-distro/eks-distro-docs-presubmits.yaml
  jobs/aws/eks-distro/kubernetes-1-21-test-presubmits.yaml
  jobs/aws/eks-distro/kubernetes-1-22-test-presubmits.yaml
  jobs/aws/eks-distro/kubernetes-1-23-test-presubmits.yaml
  jobs/aws/eks-distro/kubernetes-1-24-test-presubmits.yaml
  jobs/aws/eks-distro/main-presubmits.yaml
  templater/templates/presubmits.yaml
Labels: lgtm, approved, size/S

#439 Fixes missing && for status/done trap
  jobs/aws/eks-distro-build-tooling/aws-for-fluent-bit-helm-chart-presubmits.yaml
  jobs/aws/eks-distro-build-tooling/eks-distro-base-make-tests.yaml
  jobs/aws/eks-distro-build-tooling/eks-distro-release-presubmits.yaml
  jobs/aws/eks-distro-build-tooling/grafana-helm-chart-presubmits.yaml
  jobs/aws/eks-distro-build-tooling/helm-chart-presubmits.yaml
  jobs/aws/eks-distro-build-tooling/kops-presubmits.yaml
  jobs/aws/eks-distro-build-tooling/prometheus-helm-chart-presubmits.yaml
  jobs/aws/eks-distro-prow-jobs/prowjobs-lint-presubmits.yaml
  jobs/aws/eks-distro/cni-1-21-presubmits.yaml
  jobs/aws/eks-distro/cni-1-22-presubmits.yaml
  jobs/aws/eks-distro/cni-1-23-presubmits.yaml
  jobs/aws/eks-distro/cni-1-24-presubmits.yaml
  jobs/aws/eks-distro/eks-distro-docs-presubmits.yaml
  jobs/aws/eks-distro/kubernetes-1-21-test-presubmits.yaml
  jobs/aws/eks-distro/kubernetes-1-22-test-presubmits.yaml
  jobs/aws/eks-distro/kubernetes-1-23-test-presubmits.yaml
  jobs/aws/eks-distro/kubernetes-1-24-test-presubmits.yaml
  jobs/aws/eks-distro/main-presubmits.yaml
  templater/templates/presubmits.yaml
Labels: lgtm, approved, size/S

#440 Adds presubmit for eks-distro-base-windows
  jobs/aws/eks-distro-build-tooling/eks-distro-base-presubmits-windows.yaml
  templater/jobs/presubmit/eks-distro-build-tooling/eks-distro-base-presubmits-windows.yaml
Labels: lgtm, approved, size/L

#442 Fixes windows base presubmit
  jobs/aws/eks-distro-build-tooling/eks-distro-base-presubmits-windows.yaml
  templater/jobs/presubmit/eks-distro-build-tooling/eks-distro-base-presubmits-windows.yaml
Labels: lgtm, approved, size/XS

#444 Reduce go image resources
  jobs/aws/eks-distro-build-tooling/golang-1-15-PROD-images-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1-16-PROD-images-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1-17-PROD-images-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1-18-PROD-images-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1-19-PROD-images-postsubmits.yaml
  templater/jobs/postsubmit/eks-distro-build-tooling/golang-1-X-PROD-images-postsubmits.yaml
Labels: lgtm, approved, size/M

#445 Add duplicate job name check in linter
  jobs/aws/eks-distro-build-tooling/eks-distro-base-test-presubmits.yaml
  linter/main.go
  templater/jobs/presubmit/eks-distro-build-tooling/eks-distro-base-test-presubmits.yaml
Labels: lgtm, approved, size/M

#447 Runs livenessprobe/node-registrar on presubmit cluster
  jobs/aws/eks-distro/livenessprobe-1-21-presubmits.yaml
  jobs/aws/eks-distro/livenessprobe-1-22-presubmits.yaml
  jobs/aws/eks-distro/livenessprobe-1-23-presubmits.yaml
  jobs/aws/eks-distro/livenessprobe-1-24-presubmits.yaml
  jobs/aws/eks-distro/node-driver-registrar-1-21-presubmits.yaml
  jobs/aws/eks-distro/node-driver-registrar-1-22-presubmits.yaml
  jobs/aws/eks-distro/node-driver-registrar-1-23-presubmits.yaml
  jobs/aws/eks-distro/node-driver-registrar-1-24-presubmits.yaml
  templater/jobs/presubmit/eks-distro/livenessprobe-1-X-presubmits.yaml
  templater/jobs/presubmit/eks-distro/node-driver-registrar-1-X-presubmits.yaml
Labels: lgtm, approved, size/M

#453 Adds checks for release branch directory
  jobs/aws/eks-distro/aws-cloud-controller-manager-1-25-presubmits.yaml
  jobs/aws/eks-distro/aws-iam-authenticator-1-25-presubmits.yaml
  jobs/aws/eks-distro/build-1-25-postsubmits.yaml
  jobs/aws/eks-distro/cni-1-25-presubmits.yaml
  jobs/aws/eks-distro/coredns-1-25-presubmits.yaml
  jobs/aws/eks-distro/dev-release-1-25-postsubmits.yaml
  jobs/aws/eks-distro/etcd-1-25-presubmits.yaml
  jobs/aws/eks-distro/external-attacher-1-25-presubmits.yaml
  jobs/aws/eks-distro/external-provisioner-1-25-presubmits.yaml
  jobs/aws/eks-distro/external-resizer-1-25-presubmits.yaml
  jobs/aws/eks-distro/external-snapshotter-1-25-presubmits.yaml
  jobs/aws/eks-distro/kubernetes-1-25-presubmits.yaml
  jobs/aws/eks-distro/kubernetes-1-25-test-presubmits.yaml
  jobs/aws/eks-distro/kubernetes-release-1-25-presubmits.yaml
  jobs/aws/eks-distro/livenessprobe-1-25-presubmits.yaml
  jobs/aws/eks-distro/metrics-server-1-25-presubmits.yaml
  jobs/aws/eks-distro/node-driver-registrar-1-25-presubmits.yaml
  jobs/aws/eks-distro/prod-release-1-25-postsubmits.yaml
  templater/jobs/utils/utils.go
Labels: lgtm, approved, size/M

#455 Skip go make lint check
  linter/main.go
Labels: lgtm, approved, size/S

#457 Update list of files that skip postsubmits
  templater/jobs/postsubmit/eks-distro/build-1-X-postsubmits.yaml
Labels: lgtm, approved, size/XS
