Repository aws/eks-distro-prow-jobs, pull requests merged in 2022-11, with the labels that each got.

#399 Use postsubmits-build-account for periodici distro-base jobs
  jobs/aws/eks-distro-build-tooling/eks-distro-base-periodics-2022.yaml
  jobs/aws/eks-distro-build-tooling/eks-distro-base-periodics.yaml
  templater/jobs/periodic/eks-distro-build-tooling/eks-distro-base-periodics-2022.yaml
  templater/jobs/periodic/eks-distro-build-tooling/eks-distro-base-periodics.yaml
Labels: lgtm, approved, size/XS

#398 Move attribution periodic to run at night
  jobs/aws/eks-distro/attribution-files-periodics.yaml
  templater/jobs/periodic/eks-distro/attribution-files-periodics.yaml
Labels: lgtm, approved, size/XS

#400 Removed 1.20 jobs
  jobs/aws/eks-distro/aws-iam-authenticator-1-20-presubmits.yaml
  jobs/aws/eks-distro/build-1-20-postsubmits.yaml
  jobs/aws/eks-distro/build-1-21-postsubmits.yaml
  jobs/aws/eks-distro/build-1-22-postsubmits.yaml
  jobs/aws/eks-distro/build-1-23-postsubmits.yaml
  jobs/aws/eks-distro/build-1-24-postsubmits.yaml
  jobs/aws/eks-distro/cni-1-20-presubmits.yaml
  jobs/aws/eks-distro/coredns-1-20-presubmits.yaml
  jobs/aws/eks-distro/dev-release-1-20-postsubmits.yaml
  jobs/aws/eks-distro/etcd-1-20-presubmits.yaml
  jobs/aws/eks-distro/external-attacher-1-20-presubmits.yaml
  jobs/aws/eks-distro/external-provisioner-1-20-presubmits.yaml
  jobs/aws/eks-distro/external-resizer-1-20-presubmits.yaml
  jobs/aws/eks-distro/external-snapshotter-1-20-presubmits.yaml
  jobs/aws/eks-distro/kubernetes-1-20-presubmits.yaml
  jobs/aws/eks-distro/kubernetes-1-20-test-presubmits.yaml
  jobs/aws/eks-distro/kubernetes-release-1-20-presubmits.yaml
  jobs/aws/eks-distro/livenessprobe-1-20-presubmits.yaml
  jobs/aws/eks-distro/metrics-server-1-20-presubmits.yaml
  jobs/aws/eks-distro/node-driver-registrar-1-20-presubmits.yaml
  jobs/aws/eks-distro/prod-release-1-20-postsubmits.yaml
  templater/jobs/utils/utils.go
Labels: lgtm, approved, size/XXL

#402 Gives buildkitd more cache on postsubmit
  scripts/buildkitd-entrypoint.sh
Labels: lgtm, approved, size/XS

#403 Adds resources request to make-tests pre
  jobs/aws/eks-distro-build-tooling/eks-distro-base-make-tests.yaml
  templater/jobs/presubmit/eks-distro-build-tooling/eks-distro-base-make-tests.yaml
Labels: size/XS

#406 Renames attribution job
  jobs/aws/eks-distro/eks-distro-attribution-periodics.yaml
  templater/jobs/periodic/eks-distro/eks-distro-attribution-periodics.yaml
Labels: lgtm, approved, size/XS

#407 Fix project path var for k/k presubmits
  jobs/aws/eks-distro/kubernetes-1-21-presubmits.yaml
  jobs/aws/eks-distro/kubernetes-1-22-presubmits.yaml
  jobs/aws/eks-distro/kubernetes-1-23-presubmits.yaml
  jobs/aws/eks-distro/kubernetes-1-24-presubmits.yaml
  templater/jobs/presubmit/eks-distro/kubernetes-1-X-presubmits.yaml
Labels: lgtm, approved, size/S

#409 Split eks-d checksum out of attribution jobn
  jobs/aws/eks-distro/eks-distro-checksum-periodics.yaml
  templater/jobs/periodic/eks-distro/eks-distro-checksum-periodics.yaml
Labels: lgtm, approved, size/M

#411 Update owners
  OWNERS
Labels: lgtm, approved, size/XS

#412 Changes golang builder to new eks-d golang images
  jobs/aws/eks-distro-build-tooling/golang-1.15-ARM64-PROD-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1.15-ARM64-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1.15-PROD-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1.15-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1.15-presubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1.16-ARM64-PROD-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1.16-ARM64-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1.16-PROD-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1.16-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1.16-presubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1.17-ARM64-PROD-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1.17-ARM64-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1.17-PROD-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1.17-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1.17-presubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1.18-ARM64-PROD-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1.18-ARM64-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1.18-PROD-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1.18-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1.18-presubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1.19-ARM64-PROD-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1.19-ARM64-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1.19-PROD-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1.19-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1.19-presubmits.yaml
  templater/jobs/postsubmit/eks-distro-build-tooling/golang-1.15-ARM64-PROD-postsubmits.yaml
  templater/jobs/postsubmit/eks-distro-build-tooling/golang-1.15-ARM64-postsubmits.yaml
  templater/jobs/postsubmit/eks-distro-build-tooling/golang-1.15-PROD-postsubmits.yaml
  templater/jobs/postsubmit/eks-distro-build-tooling/golang-1.15-postsubmits.yaml
  templater/jobs/postsubmit/eks-distro-build-tooling/golang-1.16-ARM64-PROD-postsubmits.yaml
  templater/jobs/postsubmit/eks-distro-build-tooling/golang-1.16-ARM64-postsubmits.yaml
  templater/jobs/postsubmit/eks-distro-build-tooling/golang-1.16-PROD-postsubmits.yaml
  templater/jobs/postsubmit/eks-distro-build-tooling/golang-1.16-postsubmits.yaml
  templater/jobs/postsubmit/eks-distro-build-tooling/golang-1.17-ARM64-PROD-postsubmits.yaml
  templater/jobs/postsubmit/eks-distro-build-tooling/golang-1.17-ARM64-postsubmits.yaml
  templater/jobs/postsubmit/eks-distro-build-tooling/golang-1.17-PROD-postsubmits.yaml
  templater/jobs/postsubmit/eks-distro-build-tooling/golang-1.17-postsubmits.yaml
  templater/jobs/postsubmit/eks-distro-build-tooling/golang-1.18-ARM64-PROD-postsubmits.yaml
  templater/jobs/postsubmit/eks-distro-build-tooling/golang-1.18-ARM64-postsubmits.yaml
  templater/jobs/postsubmit/eks-distro-build-tooling/golang-1.18-PROD-postsubmits.yaml
  templater/jobs/postsubmit/eks-distro-build-tooling/golang-1.18-postsubmits.yaml
  templater/jobs/postsubmit/eks-distro-build-tooling/golang-1.19-ARM64-PROD-postsubmits.yaml
  templater/jobs/postsubmit/eks-distro-build-tooling/golang-1.19-ARM64-postsubmits.yaml
  templater/jobs/postsubmit/eks-distro-build-tooling/golang-1.19-PROD-postsubmits.yaml
  templater/jobs/postsubmit/eks-distro-build-tooling/golang-1.19-postsubmits.yaml
  templater/jobs/presubmit/eks-distro-build-tooling/golang-1.15-presubmits.yaml
  templater/jobs/presubmit/eks-distro-build-tooling/golang-1.16-presubmits.yaml
  templater/jobs/presubmit/eks-distro-build-tooling/golang-1.17-presubmits.yaml
  templater/jobs/presubmit/eks-distro-build-tooling/golang-1.18-presubmits.yaml
  templater/jobs/presubmit/eks-distro-build-tooling/golang-1.19-presubmits.yaml
Labels: lgtm, approved, size/L

#415 Run images target for livenessprobe and registrar
  jobs/aws/eks-distro/livenessprobe-1-21-presubmits.yaml
  jobs/aws/eks-distro/livenessprobe-1-22-presubmits.yaml
  jobs/aws/eks-distro/livenessprobe-1-23-presubmits.yaml
  jobs/aws/eks-distro/livenessprobe-1-24-presubmits.yaml
  jobs/aws/eks-distro/node-driver-registrar-1-21-presubmits.yaml
  jobs/aws/eks-distro/node-driver-registrar-1-22-presubmits.yaml
  jobs/aws/eks-distro/node-driver-registrar-1-23-presubmits.yaml
  jobs/aws/eks-distro/node-driver-registrar-1-24-presubmits.yaml
  templater/jobs/presubmit/eks-distro/livenessprobe-1-X-presubmits.yaml
  templater/jobs/presubmit/eks-distro/node-driver-registrar-1-X-presubmits.yaml
Labels: lgtm, approved, size/L

#416 Sets csi sidecar to run on postsubmit cluster
  jobs/aws/eks-distro/livenessprobe-1-21-presubmits.yaml
  jobs/aws/eks-distro/livenessprobe-1-22-presubmits.yaml
  jobs/aws/eks-distro/livenessprobe-1-23-presubmits.yaml
  jobs/aws/eks-distro/livenessprobe-1-24-presubmits.yaml
  jobs/aws/eks-distro/node-driver-registrar-1-21-presubmits.yaml
  jobs/aws/eks-distro/node-driver-registrar-1-22-presubmits.yaml
  jobs/aws/eks-distro/node-driver-registrar-1-23-presubmits.yaml
  jobs/aws/eks-distro/node-driver-registrar-1-24-presubmits.yaml
  templater/jobs/presubmit/eks-distro/livenessprobe-1-X-presubmits.yaml
  templater/jobs/presubmit/eks-distro/node-driver-registrar-1-X-presubmits.yaml
Labels: lgtm, approved, size/M

#417 add bucket in jobConfig to use in eks-A templater
  templater/jobs/types/types.go
Labels: lgtm, approved, size/XS

#418 Removes buildctl prune from distro presubmit
  jobs/aws/eks-distro-build-tooling/eks-distro-base-presubmits-golang-1-15-2022.yaml
  jobs/aws/eks-distro-build-tooling/eks-distro-base-presubmits-golang-1-15.yaml
  jobs/aws/eks-distro-build-tooling/eks-distro-base-presubmits-golang-1-16-2022.yaml
  jobs/aws/eks-distro-build-tooling/eks-distro-base-presubmits-golang-1-16.yaml
  jobs/aws/eks-distro-build-tooling/eks-distro-base-presubmits-golang-1-17-2022.yaml
  jobs/aws/eks-distro-build-tooling/eks-distro-base-presubmits-golang-1-17.yaml
  jobs/aws/eks-distro-build-tooling/eks-distro-base-presubmits-golang-1-18-2022.yaml
  jobs/aws/eks-distro-build-tooling/eks-distro-base-presubmits-golang-1-18.yaml
  jobs/aws/eks-distro-build-tooling/eks-distro-base-presubmits-golang-1-19-2022.yaml
  jobs/aws/eks-distro-build-tooling/eks-distro-base-presubmits-golang-1-19.yaml
  jobs/aws/eks-distro-build-tooling/eks-distro-base-presubmits-python-3.9-2022.yaml
  jobs/aws/eks-distro-build-tooling/eks-distro-base-presubmits-python-3.9.yaml
  templater/jobs/presubmit/eks-distro-build-tooling/eks-distro-base-presubmits-golang-1-15-2022.yaml
  templater/jobs/presubmit/eks-distro-build-tooling/eks-distro-base-presubmits-golang-1-15.yaml
  templater/jobs/presubmit/eks-distro-build-tooling/eks-distro-base-presubmits-golang-1-16-2022.yaml
  templater/jobs/presubmit/eks-distro-build-tooling/eks-distro-base-presubmits-golang-1-16.yaml
  templater/jobs/presubmit/eks-distro-build-tooling/eks-distro-base-presubmits-golang-1-17-2022.yaml
  templater/jobs/presubmit/eks-distro-build-tooling/eks-distro-base-presubmits-golang-1-17.yaml
  templater/jobs/presubmit/eks-distro-build-tooling/eks-distro-base-presubmits-golang-1-18-2022.yaml
  templater/jobs/presubmit/eks-distro-build-tooling/eks-distro-base-presubmits-golang-1-18.yaml
  templater/jobs/presubmit/eks-distro-build-tooling/eks-distro-base-presubmits-golang-1-19-2022.yaml
  templater/jobs/presubmit/eks-distro-build-tooling/eks-distro-base-presubmits-golang-1-19.yaml
  templater/jobs/presubmit/eks-distro-build-tooling/eks-distro-base-presubmits-python-3.9-2022.yaml
  templater/jobs/presubmit/eks-distro-build-tooling/eks-distro-base-presubmits-python-3.9.yaml
Labels: lgtm, approved, size/M
