Repository aws/eks-distro-prow-jobs, pull requests merged in 2022-02, with the labels that each got.

#263 Added jobs for 1-22
  jobs/aws/eks-distro/aws-iam-authenticator-1-22-presubmits.yaml
  jobs/aws/eks-distro/build-1-22-postsubmits.yaml
  jobs/aws/eks-distro/coredns-1-22-presubmits.yaml
  jobs/aws/eks-distro/dev-release-1-22-postsubmits.yaml
  jobs/aws/eks-distro/etcd-1-22-presubmits.yaml
  jobs/aws/eks-distro/kubernetes-1-22-presubmits.yaml
  jobs/aws/eks-distro/kubernetes-1-22-test-presubmits.yaml
  jobs/aws/eks-distro/kubernetes-release-1-22-presubmits.yaml
  jobs/aws/eks-distro/metrics-server-1-22-presubmits.yaml
  jobs/aws/eks-distro/prod-release-1-22-postsubmits.yaml
  templater/jobs/utils/utils.go
Labels: lgtm, approved, size/XL

#264 remove 1.21 minimal postsubmit
  jobs/aws/eks-distro/build-1-21-minimal-postsubmits.yaml
  templater/jobs/postsubmit/eks-distro/build-1-21-minimal-postsubmits.yaml
Labels: lgtm, approved, size/L

#266 Split CSI Snapshotter
  jobs/aws/eks-distro/external-snapshotter-1-18-presubmits.yaml
  jobs/aws/eks-distro/external-snapshotter-1-19-presubmits.yaml
  jobs/aws/eks-distro/external-snapshotter-1-20-presubmits.yaml
  jobs/aws/eks-distro/external-snapshotter-1-21-presubmits.yaml
  jobs/aws/eks-distro/external-snapshotter-1-22-presubmits.yaml
  templater/jobs/presubmit/eks-distro/external-snapshotter-1-X-presubmits.yaml
Labels: lgtm, approved, size/L

#267 fix kuberentes presubmit resources requests
  jobs/aws/eks-distro/kubernetes-1-18-presubmits.yaml
  jobs/aws/eks-distro/kubernetes-1-19-presubmits.yaml
  jobs/aws/eks-distro/kubernetes-1-20-presubmits.yaml
  jobs/aws/eks-distro/kubernetes-1-21-presubmits.yaml
  jobs/aws/eks-distro/kubernetes-1-22-presubmits.yaml
  templater/jobs/presubmit/eks-distro/kubernetes-1-X-presubmits.yaml
Labels: lgtm, approved, size/M

#268 Delete external-snapshotter-presubmits.yaml
  jobs/aws/eks-distro/external-snapshotter-presubmits.yaml
Labels: lgtm, approved, size/M

#269 main-presubmit is just a dry run at this point, dropping resources
  jobs/aws/eks-distro/main-presubmits.yaml
  templater/jobs/presubmit/eks-distro/main-presubmits.yaml
Labels: lgtm, approved, size/M

#270 Delete jobs if templates are deleted
  templater/main.go
Labels: lgtm, approved, size/M

#275 eks-distro-base: appened al_tag in prow job
  jobs/aws/eks-distro-build-tooling/eks-distro-base-periodics-2022.yaml
  jobs/aws/eks-distro-build-tooling/eks-distro-base-periodics.yaml
  jobs/aws/eks-distro-build-tooling/eks-distro-base-postsubmits-2022.yaml
  jobs/aws/eks-distro-build-tooling/eks-distro-base-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/eks-distro-base-presubmit-2022.yaml
  templater/jobs/periodic/eks-distro-build-tooling/eks-distro-base-periodics-2022.yaml
  templater/jobs/periodic/eks-distro-build-tooling/eks-distro-base-periodics.yaml
  templater/jobs/postsubmit/eks-distro-build-tooling/eks-distro-base-postsubmits-2022.yaml
  templater/jobs/postsubmit/eks-distro-build-tooling/eks-distro-base-postsubmits.yaml
  templater/jobs/presubmit/eks-distro-build-tooling/eks-distro-base-presubmit-2022.yaml
Labels: lgtm, approved, size/M

#277 bump eks-distro-base job timeouts
  jobs/aws/eks-distro-build-tooling/eks-distro-base-periodics-2022.yaml
  jobs/aws/eks-distro-build-tooling/eks-distro-base-periodics.yaml
  jobs/aws/eks-distro-build-tooling/eks-distro-base-postsubmits-2022.yaml
  jobs/aws/eks-distro-build-tooling/eks-distro-base-postsubmits.yaml
  templater/jobs/periodic/eks-distro-build-tooling/eks-distro-base-periodics-2022.yaml
  templater/jobs/periodic/eks-distro-build-tooling/eks-distro-base-periodics.yaml
  templater/jobs/postsubmit/eks-distro-build-tooling/eks-distro-base-postsubmits-2022.yaml
  templater/jobs/postsubmit/eks-distro-build-tooling/eks-distro-base-postsubmits.yaml
Labels: lgtm, approved, size/XS

#279 new job for updating base image tag files across repos
  jobs/aws/eks-distro-build-tooling/eks-distro-base-tag-files-update-postsubmit.yaml
  templater/jobs/postsubmit/eks-distro-build-tooling/eks-distro-base-tag-files-update-postsubmit.yaml
Labels: lgtm, approved, size/M

#281 Add prowjobs to build Prow deck image
  jobs/aws/eks-distro-build-tooling/prow-deck-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/prow-deck-presubmits.yaml
  templater/jobs/postsubmit/eks-distro-build-tooling/prow-deck-postsubmits.yaml
  templater/jobs/presubmit/eks-distro-build-tooling/prow-deck-presubmits.yaml
Labels: lgtm, approved, size/L

#283 Make livenessprobe less aggressive
  jobs/aws/eks-distro-build-tooling/alertmanager-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/amazon-eks-pod-identity-webhook-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/athens-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/builder-base-postsubmits-2022.yaml
  jobs/aws/eks-distro-build-tooling/builder-base-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/eks-distro-base-postsubmits-2022.yaml
  jobs/aws/eks-distro-build-tooling/eks-distro-base-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/eks-distro-base-presubmit-2022.yaml
  jobs/aws/eks-distro-build-tooling/eks-distro-base-presubmits.yaml
  jobs/aws/eks-distro-build-tooling/github-exporter-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/prometheus-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/prow-deck-postsubmits.yaml
  jobs/aws/eks-distro/build-1-18-postsubmits.yaml
  jobs/aws/eks-distro/build-1-19-postsubmits.yaml
  jobs/aws/eks-distro/build-1-20-postsubmits.yaml
  jobs/aws/eks-distro/build-1-21-postsubmits.yaml
  jobs/aws/eks-distro/build-1-22-postsubmits.yaml
  jobs/aws/eks-distro/dev-release-1-18-postsubmits.yaml
  jobs/aws/eks-distro/dev-release-1-19-postsubmits.yaml
  jobs/aws/eks-distro/dev-release-1-20-postsubmits.yaml
  jobs/aws/eks-distro/dev-release-1-21-postsubmits.yaml
  jobs/aws/eks-distro/dev-release-1-22-postsubmits.yaml
  jobs/aws/eks-distro/kubernetes-1-18-presubmits.yaml
  jobs/aws/eks-distro/kubernetes-1-19-presubmits.yaml
  jobs/aws/eks-distro/kubernetes-1-20-presubmits.yaml
  jobs/aws/eks-distro/kubernetes-1-21-presubmits.yaml
  jobs/aws/eks-distro/kubernetes-1-22-presubmits.yaml
  jobs/aws/eks-distro/prod-release-1-18-postsubmits.yaml
  jobs/aws/eks-distro/prod-release-1-19-postsubmits.yaml
  jobs/aws/eks-distro/prod-release-1-20-postsubmits.yaml
  jobs/aws/eks-distro/prod-release-1-21-postsubmits.yaml
  jobs/aws/eks-distro/prod-release-1-22-postsubmits.yaml
  templater/templates/periodics.yaml
  templater/templates/postsubmits.yaml
  templater/templates/presubmits.yaml
Labels: lgtm, approved, size/M

#285 eks-distro attribution: bump timeout up to handle new kube build
  jobs/aws/eks-distro/attribution-files-periodics.yaml
  templater/jobs/periodic/eks-distro/attribution-files-periodics.yaml
Labels: lgtm, approved, size/XS

#289 Enable garbage collection on buildkit worker
  scripts/buildkitd-entrypoint.sh
Labels: lgtm, approved, size/XS
