Repository aws/eks-distro-prow-jobs, pull requests merged in 2022-04, with the labels that each got.

#300 Deleted 1-18 jobs
  jobs/aws/eks-distro/aws-iam-authenticator-1-18-presubmits.yaml
  jobs/aws/eks-distro/build-1-18-postsubmits.yaml
  jobs/aws/eks-distro/coredns-1-18-presubmits.yaml
  jobs/aws/eks-distro/dev-release-1-18-postsubmits.yaml
  jobs/aws/eks-distro/etcd-1-18-presubmits.yaml
  jobs/aws/eks-distro/external-attacher-1-18-presubmits.yaml
  jobs/aws/eks-distro/external-provisioner-1-18-presubmits.yaml
  jobs/aws/eks-distro/external-resizer-1-18-presubmits.yaml
  jobs/aws/eks-distro/external-snapshotter-1-18-presubmits.yaml
  jobs/aws/eks-distro/kubernetes-1-18-presubmits.yaml
  jobs/aws/eks-distro/kubernetes-1-18-test-presubmits.yaml
  jobs/aws/eks-distro/kubernetes-release-1-18-presubmits.yaml
  jobs/aws/eks-distro/livenessprobe-1-18-presubmits.yaml
  jobs/aws/eks-distro/metrics-server-1-18-presubmits.yaml
  jobs/aws/eks-distro/node-driver-registrar-1-18-presubmits.yaml
  jobs/aws/eks-distro/prod-release-1-18-postsubmits.yaml
  templater/jobs/utils/utils.go
Labels: lgtm, approved, size/XXL

#302 Mount BUILDER_BASE_TAG_FILE onto Prowjob pods as ConfigMap
  jobs/presets.yaml
  scripts/buildkitd-entrypoint.sh
Labels: lgtm, approved, size/S

#304 properly handle running out of disk space in presubmit
  jobs/aws/eks-distro-build-tooling/alertmanager-presubmits.yaml
  jobs/aws/eks-distro-build-tooling/amazon-eks-pod-identity-webhook-presubmits.yaml
  jobs/aws/eks-distro-build-tooling/athens-presubmits.yaml
  jobs/aws/eks-distro-build-tooling/builder-base-presubmits-2022.yaml
  jobs/aws/eks-distro-build-tooling/builder-base-presubmits.yaml
  jobs/aws/eks-distro-build-tooling/eks-distro-base-presubmit-2022.yaml
  jobs/aws/eks-distro-build-tooling/eks-distro-base-presubmits.yaml
  jobs/aws/eks-distro-build-tooling/github-exporter-presubmits.yaml
  jobs/aws/eks-distro-build-tooling/prometheus-presubmits.yaml
  jobs/aws/eks-distro-build-tooling/prow-deck-presubmits.yaml
  jobs/aws/eks-distro/aws-iam-authenticator-1-19-presubmits.yaml
  jobs/aws/eks-distro/aws-iam-authenticator-1-20-presubmits.yaml
  jobs/aws/eks-distro/aws-iam-authenticator-1-21-presubmits.yaml
  jobs/aws/eks-distro/aws-iam-authenticator-1-22-presubmits.yaml
  jobs/aws/eks-distro/coredns-1-19-presubmits.yaml
  jobs/aws/eks-distro/coredns-1-20-presubmits.yaml
  jobs/aws/eks-distro/coredns-1-21-presubmits.yaml
  jobs/aws/eks-distro/coredns-1-22-presubmits.yaml
  jobs/aws/eks-distro/etcd-1-19-presubmits.yaml
  jobs/aws/eks-distro/etcd-1-20-presubmits.yaml
  jobs/aws/eks-distro/etcd-1-21-presubmits.yaml
  jobs/aws/eks-distro/etcd-1-22-presubmits.yaml
  jobs/aws/eks-distro/external-attacher-1-19-presubmits.yaml
  jobs/aws/eks-distro/external-attacher-1-20-presubmits.yaml
  jobs/aws/eks-distro/external-attacher-1-21-presubmits.yaml
  jobs/aws/eks-distro/external-attacher-1-22-presubmits.yaml
  jobs/aws/eks-distro/external-provisioner-1-19-presubmits.yaml
  jobs/aws/eks-distro/external-provisioner-1-20-presubmits.yaml
  jobs/aws/eks-distro/external-provisioner-1-21-presubmits.yaml
  jobs/aws/eks-distro/external-provisioner-1-22-presubmits.yaml
  jobs/aws/eks-distro/external-resizer-1-19-presubmits.yaml
  jobs/aws/eks-distro/external-resizer-1-20-presubmits.yaml
  jobs/aws/eks-distro/external-resizer-1-21-presubmits.yaml
  jobs/aws/eks-distro/external-resizer-1-22-presubmits.yaml
  jobs/aws/eks-distro/external-snapshotter-1-19-presubmits.yaml
  jobs/aws/eks-distro/external-snapshotter-1-20-presubmits.yaml
  jobs/aws/eks-distro/external-snapshotter-1-21-presubmits.yaml
  jobs/aws/eks-distro/external-snapshotter-1-22-presubmits.yaml
  jobs/aws/eks-distro/kubernetes-1-19-presubmits.yaml
  jobs/aws/eks-distro/kubernetes-1-20-presubmits.yaml
  jobs/aws/eks-distro/kubernetes-1-21-presubmits.yaml
  jobs/aws/eks-distro/kubernetes-1-22-presubmits.yaml
  jobs/aws/eks-distro/kubernetes-release-1-19-presubmits.yaml
  jobs/aws/eks-distro/kubernetes-release-1-20-presubmits.yaml
  jobs/aws/eks-distro/kubernetes-release-1-21-presubmits.yaml
  jobs/aws/eks-distro/kubernetes-release-1-22-presubmits.yaml
  jobs/aws/eks-distro/livenessprobe-1-19-presubmits.yaml
  jobs/aws/eks-distro/livenessprobe-1-20-presubmits.yaml
  jobs/aws/eks-distro/livenessprobe-1-21-presubmits.yaml
  jobs/aws/eks-distro/livenessprobe-1-22-presubmits.yaml
  jobs/aws/eks-distro/metrics-server-1-19-presubmits.yaml
  jobs/aws/eks-distro/metrics-server-1-20-presubmits.yaml
  jobs/aws/eks-distro/metrics-server-1-21-presubmits.yaml
  jobs/aws/eks-distro/metrics-server-1-22-presubmits.yaml
  jobs/aws/eks-distro/node-driver-registrar-1-19-presubmits.yaml
  jobs/aws/eks-distro/node-driver-registrar-1-20-presubmits.yaml
  jobs/aws/eks-distro/node-driver-registrar-1-21-presubmits.yaml
  jobs/aws/eks-distro/node-driver-registrar-1-22-presubmits.yaml
  templater/templates/presubmits.yaml
Labels: lgtm, approved, size/L

#305 Added skip_if_only_changed to postsubmit builds
  docs/prowjobs.md
  jobs/aws/eks-distro/build-1-19-postsubmits.yaml
  jobs/aws/eks-distro/build-1-20-postsubmits.yaml
  jobs/aws/eks-distro/build-1-21-postsubmits.yaml
  jobs/aws/eks-distro/build-1-22-postsubmits.yaml
  templater/jobs/postsubmit/eks-distro/build-1-X-postsubmits.yaml
  templater/jobs/types/types.go
  templater/jobs/utils/utils.go
  templater/main.go
  templater/templates/postsubmits.yaml
Labels: lgtm, approved, size/M

#307 Reduce Buildkit GC storage to 5 GB
  scripts/buildkitd-entrypoint.sh
Labels: lgtm, approved, size/XS

#306 Add markapruett to owners
  OWNERS
Labels: lgtm, approved, size/XS

#310 only run presubmit for version changed
  jobs/aws/eks-distro/aws-iam-authenticator-1-19-presubmits.yaml
  jobs/aws/eks-distro/aws-iam-authenticator-1-20-presubmits.yaml
  jobs/aws/eks-distro/aws-iam-authenticator-1-21-presubmits.yaml
  jobs/aws/eks-distro/aws-iam-authenticator-1-22-presubmits.yaml
  jobs/aws/eks-distro/coredns-1-19-presubmits.yaml
  jobs/aws/eks-distro/coredns-1-20-presubmits.yaml
  jobs/aws/eks-distro/coredns-1-21-presubmits.yaml
  jobs/aws/eks-distro/coredns-1-22-presubmits.yaml
  jobs/aws/eks-distro/etcd-1-19-presubmits.yaml
  jobs/aws/eks-distro/etcd-1-20-presubmits.yaml
  jobs/aws/eks-distro/etcd-1-21-presubmits.yaml
  jobs/aws/eks-distro/etcd-1-22-presubmits.yaml
  jobs/aws/eks-distro/external-attacher-1-19-presubmits.yaml
  jobs/aws/eks-distro/external-attacher-1-20-presubmits.yaml
  jobs/aws/eks-distro/external-attacher-1-21-presubmits.yaml
  jobs/aws/eks-distro/external-attacher-1-22-presubmits.yaml
  jobs/aws/eks-distro/external-provisioner-1-19-presubmits.yaml
  jobs/aws/eks-distro/external-provisioner-1-20-presubmits.yaml
  jobs/aws/eks-distro/external-provisioner-1-21-presubmits.yaml
  jobs/aws/eks-distro/external-provisioner-1-22-presubmits.yaml
  jobs/aws/eks-distro/external-resizer-1-19-presubmits.yaml
  jobs/aws/eks-distro/external-resizer-1-20-presubmits.yaml
  jobs/aws/eks-distro/external-resizer-1-21-presubmits.yaml
  jobs/aws/eks-distro/external-resizer-1-22-presubmits.yaml
  jobs/aws/eks-distro/external-snapshotter-1-19-presubmits.yaml
  jobs/aws/eks-distro/external-snapshotter-1-20-presubmits.yaml
  jobs/aws/eks-distro/external-snapshotter-1-21-presubmits.yaml
  jobs/aws/eks-distro/external-snapshotter-1-22-presubmits.yaml
  jobs/aws/eks-distro/kubernetes-release-1-19-presubmits.yaml
  jobs/aws/eks-distro/kubernetes-release-1-20-presubmits.yaml
  jobs/aws/eks-distro/kubernetes-release-1-21-presubmits.yaml
  jobs/aws/eks-distro/kubernetes-release-1-22-presubmits.yaml
  jobs/aws/eks-distro/livenessprobe-1-19-presubmits.yaml
  jobs/aws/eks-distro/livenessprobe-1-20-presubmits.yaml
  jobs/aws/eks-distro/livenessprobe-1-21-presubmits.yaml
  jobs/aws/eks-distro/livenessprobe-1-22-presubmits.yaml
  jobs/aws/eks-distro/metrics-server-1-19-presubmits.yaml
  jobs/aws/eks-distro/metrics-server-1-20-presubmits.yaml
  jobs/aws/eks-distro/metrics-server-1-21-presubmits.yaml
  jobs/aws/eks-distro/metrics-server-1-22-presubmits.yaml
  jobs/aws/eks-distro/node-driver-registrar-1-19-presubmits.yaml
  jobs/aws/eks-distro/node-driver-registrar-1-20-presubmits.yaml
  jobs/aws/eks-distro/node-driver-registrar-1-21-presubmits.yaml
  jobs/aws/eks-distro/node-driver-registrar-1-22-presubmits.yaml
  templater/jobs/presubmit/eks-distro/aws-iam-authenticator-1-X-presubmits.yaml
  templater/jobs/presubmit/eks-distro/coredns-1-X-presubmits.yaml
  templater/jobs/presubmit/eks-distro/etcd-1-X-presubmits.yaml
  templater/jobs/presubmit/eks-distro/external-attacher-1-X-presubmits.yaml
  templater/jobs/presubmit/eks-distro/external-provisioner-1-X-presubmits.yaml
  templater/jobs/presubmit/eks-distro/external-resizer-1-X-presubmits.yaml
  templater/jobs/presubmit/eks-distro/external-snapshotter-1-X-presubmits.yaml
  templater/jobs/presubmit/eks-distro/kubernetes-release-1-X-presubmits.yaml
  templater/jobs/presubmit/eks-distro/livenessprobe-1-X-presubmits.yaml
  templater/jobs/presubmit/eks-distro/metrics-server-1-X-presubmits.yaml
  templater/jobs/presubmit/eks-distro/node-driver-registrar-1-X-presubmits.yaml
Labels: lgtm, approved, size/L
