Repository aws/eks-distro-prow-jobs, pull requests merged in 2023-11, with the labels that each got.

#562 Add CNI-plugin tests
  jobs/aws/eks-distro/cni-1-23-test-presubmits.yaml
  jobs/aws/eks-distro/cni-1-24-test-presubmits.yaml
  jobs/aws/eks-distro/cni-1-25-test-presubmits.yaml
  jobs/aws/eks-distro/cni-1-26-test-presubmits.yaml
  jobs/aws/eks-distro/cni-1-27-test-presubmits.yaml
  jobs/aws/eks-distro/cni-1-28-test-presubmits.yaml
  templater/jobs/presubmit/eks-distro/cni-1-X-test-presubmits.yaml
Labels: lgtm, approved, size/L

#565 Exclude 1-23 jobs from Prowjob Linter
  templater/scripts/verify-prowjobs.sh
Labels: lgtm, approved, size/XS

#566 Update verify_prowjob script
  templater/scripts/verify-prowjobs.sh
Labels: lgtm, approved, size/XS

#564 Remove 1.23 Prowjobs K8 presubmit tests and Update CNI-plugin tests triggeres
  jobs/aws/eks-distro/aws-cloud-controller-manager-1-23-presubmits.yaml
  jobs/aws/eks-distro/aws-iam-authenticator-1-23-presubmits.yaml
  jobs/aws/eks-distro/build-1-23-postsubmits.yaml
  jobs/aws/eks-distro/build-1-24-postsubmits.yaml
  jobs/aws/eks-distro/build-1-25-postsubmits.yaml
  jobs/aws/eks-distro/build-1-26-postsubmits.yaml
  jobs/aws/eks-distro/build-1-27-postsubmits.yaml
  jobs/aws/eks-distro/build-1-28-postsubmits.yaml
  jobs/aws/eks-distro/cni-1-23-presubmits.yaml
  jobs/aws/eks-distro/cni-1-23-test-presubmits.yaml
  jobs/aws/eks-distro/cni-1-24-test-presubmits.yaml
  jobs/aws/eks-distro/cni-1-25-test-presubmits.yaml
  jobs/aws/eks-distro/cni-1-26-test-presubmits.yaml
  jobs/aws/eks-distro/cni-1-27-test-presubmits.yaml
  jobs/aws/eks-distro/cni-1-28-test-presubmits.yaml
  jobs/aws/eks-distro/coredns-1-23-presubmits.yaml
  jobs/aws/eks-distro/dev-release-1-23-postsubmits.yaml
  jobs/aws/eks-distro/etcd-1-23-presubmits.yaml
  jobs/aws/eks-distro/external-attacher-1-23-presubmits.yaml
  jobs/aws/eks-distro/external-provisioner-1-23-presubmits.yaml
  jobs/aws/eks-distro/external-resizer-1-23-presubmits.yaml
  jobs/aws/eks-distro/external-snapshotter-1-23-presubmits.yaml
  jobs/aws/eks-distro/kops-build-1-23-presubmits.yaml
  jobs/aws/eks-distro/kubernetes-release-1-23-presubmits.yaml
  jobs/aws/eks-distro/livenessprobe-1-23-presubmits.yaml
  jobs/aws/eks-distro/metrics-server-1-23-presubmits.yaml
  jobs/aws/eks-distro/node-driver-registrar-1-23-presubmits.yaml
  jobs/aws/eks-distro/prod-release-1-23-postsubmits.yaml
  templater/jobs/presubmit/eks-distro/cni-1-X-test-presubmits.yaml
  templater/jobs/utils/utils.go
  templater/scripts/verify-prowjobs.sh
Labels: lgtm, approved, size/XXL

#567 Update CNI-plugin unit tests triggers
  jobs/aws/eks-distro/cni-1-24-test-presubmits.yaml
  jobs/aws/eks-distro/cni-1-25-test-presubmits.yaml
  jobs/aws/eks-distro/cni-1-26-test-presubmits.yaml
  jobs/aws/eks-distro/cni-1-27-test-presubmits.yaml
  jobs/aws/eks-distro/cni-1-28-test-presubmits.yaml
  templater/jobs/presubmit/eks-distro/cni-1-X-test-presubmits.yaml
Labels: lgtm, approved, size/S

#571 Remove CNI tests prowjobs due to WIP state
  jobs/aws/eks-distro/cni-1-24-test-presubmits.yaml
  jobs/aws/eks-distro/cni-1-25-test-presubmits.yaml
  jobs/aws/eks-distro/cni-1-26-test-presubmits.yaml
  jobs/aws/eks-distro/cni-1-27-test-presubmits.yaml
  jobs/aws/eks-distro/cni-1-28-test-presubmits.yaml
  jobs/aws/eks-distro/cni-1-29-test-presubmits.yaml
  templater/jobs/presubmit/eks-distro/cni-1-X-test-presubmits.yaml
Labels: lgtm, approved, size/L
