Repository aws/eks-distro-prow-jobs, pull requests merged in 2023-09, with the labels that each got.

#537 Request ephemeral storage to run 1-28-test-presubmit on fargate
  jobs/aws/eks-distro/kubernetes-1-28-test-presubmits.yaml
  linter/main.go
  templater/jobs/presubmit/eks-distro/kubernetes-1-X-test-presubmits.yaml
  templater/jobs/types/types.go
  templater/templates/presubmits.yaml
Labels: lgtm, approved, size/M

#538 Configure ephemeral storage to be a standard resource
  jobs/aws/eks-distro/kubernetes-1-28-test-presubmits.yaml
  templater/jobs/presubmit/eks-distro/kubernetes-1-X-test-presubmits.yaml
  templater/jobs/types/types.go
  templater/templates/presubmits.yaml
Labels: lgtm, approved, size/XS

#539 Request ephemeral-storage for 1-27-test-presubmit
  jobs/aws/eks-distro/kubernetes-1-27-test-presubmits.yaml
  linter/main.go
  templater/jobs/presubmit/eks-distro/kubernetes-1-X-test-presubmits.yaml
Labels: lgtm, approved, size/M

#540 Remove go1.18 prowjobs
  jobs/aws/eks-distro-build-tooling/eks-distro-base-presubmits-golang-1-18-al-2.yaml
  jobs/aws/eks-distro-build-tooling/eks-distro-base-presubmits-golang-1-18-al-2023.yaml
  jobs/aws/eks-distro-build-tooling/golang-1-18-ARM64-PROD-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1-18-ARM64-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1-18-PROD-images-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1-18-PROD-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1-18-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1-18-presubmits.yaml
  templater/jobs/utils/utils.go
Labels: lgtm, approved, size/XL

#543 Update storage size for kops-presubmits
  jobs/aws/eks-distro-build-tooling/kops-presubmits.yaml
  templater/jobs/presubmit/eks-distro-build-tooling/kops-presubmits.yaml
Labels: lgtm, approved, size/XS

#546 Request ephemeral storage to run 1.25,1.26 test presubmits
  jobs/aws/eks-distro/kubernetes-1-25-test-presubmits.yaml
  jobs/aws/eks-distro/kubernetes-1-26-test-presubmits.yaml
  templater/jobs/presubmit/eks-distro/kubernetes-1-X-test-presubmits.yaml
Labels: lgtm, approved, size/XS
