Repository aws/eks-distro-prow-jobs, pull requests merged in 2023-08, with the labels that each got.

#521 Added sns notification to golang post-submits
  jobs/aws/eks-distro-build-tooling/golang-1-18-PROD-images-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1-18-PROD-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1-19-PROD-images-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1-19-PROD-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1-20-PROD-images-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1-20-PROD-postsubmits.yaml
  templater/jobs/postsubmit/eks-distro-build-tooling/golang-1-X-PROD-images-postsubmits.yaml
  templater/jobs/postsubmit/eks-distro-build-tooling/golang-1-X-PROD-postsubmits.yaml
Labels: lgtm, approved, size/M

#528 Move 1-28-test-presubmits job to different cluster
  jobs/aws/eks-distro/kubernetes-1-28-test-presubmits.yaml
  linter/main.go
  templater/jobs/presubmit/eks-distro/kubernetes-1-X-test-presubmits.yaml
Labels: lgtm, approved, size/S

#529 Added role to golang image updates
  jobs/aws/eks-distro-build-tooling/golang-1-18-PROD-images-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1-19-PROD-images-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1-20-PROD-images-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1-21-PROD-images-postsubmits.yaml
  templater/jobs/postsubmit/eks-distro-build-tooling/golang-1-X-PROD-images-postsubmits.yaml
Labels: lgtm, approved, size/S

#530 Update go mod
  go.mod
  go.sum
Labels: lgtm, approved, size/XL

#533 Add 1.20 for Prowjob Liner
  linter/Makefile
Labels: lgtm, approved, size/XS

#534 Fix go.mod for linter
  go.mod
Labels: lgtm, approved, ok-to-test, size/XS

#536 Fix go mod to run linter
  go.mod
  go.sum
Labels: lgtm, approved, size/L
