Repository aws/eks-distro-prow-jobs, pull requests merged in 2024-07, with the labels that each got.

#612 update prow jobs for 1.25 and 1.26 deprecation
  jobs/aws/eks-distro/aws-cloud-controller-manager-1-25-presubmits.yaml
  jobs/aws/eks-distro/aws-cloud-controller-manager-1-26-presubmits.yaml
  jobs/aws/eks-distro/aws-iam-authenticator-1-25-presubmits.yaml
  jobs/aws/eks-distro/aws-iam-authenticator-1-26-presubmits.yaml
  jobs/aws/eks-distro/build-1-25-postsubmits.yaml
  jobs/aws/eks-distro/build-1-26-postsubmits.yaml
  jobs/aws/eks-distro/build-1-27-postsubmits.yaml
  jobs/aws/eks-distro/build-1-28-postsubmits.yaml
  jobs/aws/eks-distro/build-1-29-postsubmits.yaml
  jobs/aws/eks-distro/build-1-30-postsubmits.yaml
  jobs/aws/eks-distro/cni-1-25-presubmits.yaml
  jobs/aws/eks-distro/cni-1-26-presubmits.yaml
  jobs/aws/eks-distro/coredns-1-25-presubmits.yaml
  jobs/aws/eks-distro/coredns-1-26-presubmits.yaml
  jobs/aws/eks-distro/dev-release-1-25-postsubmits.yaml
  jobs/aws/eks-distro/dev-release-1-26-postsubmits.yaml
  jobs/aws/eks-distro/etcd-1-25-presubmits.yaml
  jobs/aws/eks-distro/etcd-1-26-presubmits.yaml
  jobs/aws/eks-distro/external-attacher-1-25-presubmits.yaml
  jobs/aws/eks-distro/external-attacher-1-26-presubmits.yaml
  jobs/aws/eks-distro/external-provisioner-1-25-presubmits.yaml
  jobs/aws/eks-distro/external-provisioner-1-26-presubmits.yaml
  jobs/aws/eks-distro/external-resizer-1-25-presubmits.yaml
  jobs/aws/eks-distro/external-resizer-1-26-presubmits.yaml
  jobs/aws/eks-distro/external-snapshotter-1-25-presubmits.yaml
  jobs/aws/eks-distro/external-snapshotter-1-26-presubmits.yaml
  jobs/aws/eks-distro/kops-build-1-25-presubmits.yaml
  jobs/aws/eks-distro/kops-build-1-26-presubmits.yaml
  jobs/aws/eks-distro/kubernetes-release-1-25-presubmits.yaml
  jobs/aws/eks-distro/kubernetes-release-1-26-presubmits.yaml
  jobs/aws/eks-distro/livenessprobe-1-25-presubmits.yaml
  jobs/aws/eks-distro/livenessprobe-1-26-presubmits.yaml
  jobs/aws/eks-distro/metrics-server-1-25-presubmits.yaml
  jobs/aws/eks-distro/metrics-server-1-26-presubmits.yaml
  jobs/aws/eks-distro/node-driver-registrar-1-25-presubmits.yaml
  jobs/aws/eks-distro/node-driver-registrar-1-26-presubmits.yaml
  jobs/aws/eks-distro/prod-release-1-25-postsubmits.yaml
  jobs/aws/eks-distro/prod-release-1-26-postsubmits.yaml
  templater/jobs/utils/utils.go
Labels: lgtm, approved, size/XXL

#617 Add periodic for checking and releasing new golang images
  jobs/aws/eks-distro-build-tooling/check_upstream_golang_release.yaml
  templater/jobs/periodic/eks-distro-build-tooling/check_upstream_golang_release.yaml
Labels: lgtm, approved, size/L

#620 update OWNERS
  OWNERS
Labels: lgtm, approved, size/XS

#621 Deprecate EKS Go 1.20 and use new make target for future debian images
  jobs/aws/eks-distro-build-tooling/eks-distro-base-presubmits-golang-1-20-al-2.yaml
  jobs/aws/eks-distro-build-tooling/eks-distro-base-presubmits-golang-1-20-al-2023.yaml
  jobs/aws/eks-distro-build-tooling/golang-1-20-ARM64-PROD-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1-20-ARM64-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1-20-PROD-images-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1-20-PROD-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1-20-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1-20-presubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1-21-PROD-images-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1-21-presubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1-22-PROD-images-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1-22-presubmits.yaml
  templater/jobs/postsubmit/eks-distro-build-tooling/golang-1-X-PROD-images-postsubmits.yaml
  templater/jobs/postsubmit/eks-distro-build-tooling/golang-1-X-PROD-postsubmits.yaml
  templater/jobs/presubmit/eks-distro-build-tooling/golang-1-X-presubmits.yaml
  templater/jobs/utils/utils.go
Labels: lgtm, approved, size/XL
