Repository aws/eks-distro-prow-jobs, pull requests merged in 2024-02, with the labels that each got.

#589 Remove 1.24 prowjobs
  jobs/aws/eks-distro/aws-cloud-controller-manager-1-24-presubmits.yaml
  jobs/aws/eks-distro/aws-iam-authenticator-1-24-presubmits.yaml
  jobs/aws/eks-distro/build-1-24-postsubmits.yaml
  jobs/aws/eks-distro/build-1-25-postsubmits.yaml
  jobs/aws/eks-distro/build-1-26-postsubmits.yaml
  jobs/aws/eks-distro/build-1-27-postsubmits.yaml
  jobs/aws/eks-distro/build-1-28-postsubmits.yaml
  jobs/aws/eks-distro/build-1-29-postsubmits.yaml
  jobs/aws/eks-distro/cni-1-24-presubmits.yaml
  jobs/aws/eks-distro/coredns-1-24-presubmits.yaml
  jobs/aws/eks-distro/dev-release-1-24-postsubmits.yaml
  jobs/aws/eks-distro/etcd-1-24-presubmits.yaml
  jobs/aws/eks-distro/external-attacher-1-24-presubmits.yaml
  jobs/aws/eks-distro/external-provisioner-1-24-presubmits.yaml
  jobs/aws/eks-distro/external-resizer-1-24-presubmits.yaml
  jobs/aws/eks-distro/external-snapshotter-1-24-presubmits.yaml
  jobs/aws/eks-distro/kops-build-1-24-presubmits.yaml
  jobs/aws/eks-distro/kubernetes-release-1-24-presubmits.yaml
  jobs/aws/eks-distro/livenessprobe-1-24-presubmits.yaml
  jobs/aws/eks-distro/metrics-server-1-24-presubmits.yaml
  jobs/aws/eks-distro/node-driver-registrar-1-24-presubmits.yaml
  jobs/aws/eks-distro/prod-release-1-24-postsubmits.yaml
  templater/jobs/utils/utils.go
Labels: lgtm, approved, size/XXL

#590 Add support for EKS Go 1.22 and deprecate EKS Go 1.19
  jobs/aws/eks-distro-build-tooling/eks-distro-base-presubmits-golang-1-22-al-2.yaml
  jobs/aws/eks-distro-build-tooling/eks-distro-base-presubmits-golang-1-22-al-2023.yaml
  jobs/aws/eks-distro-build-tooling/golang-1-22-ARM64-PROD-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1-22-ARM64-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1-22-PROD-images-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1-22-PROD-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1-22-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1-22-presubmits.yaml
  templater/jobs/utils/utils.go
Labels: lgtm, approved, size/M

#569 Add Go version trigger in kubernetes Unit tests
  jobs/aws/eks-distro/kubernetes-1-23-test-presubmits.yaml
  jobs/aws/eks-distro/kubernetes-1-24-test-presubmits.yaml
  jobs/aws/eks-distro/kubernetes-1-25-test-presubmits.yaml
  jobs/aws/eks-distro/kubernetes-1-26-test-presubmits.yaml
  jobs/aws/eks-distro/kubernetes-1-27-test-presubmits.yaml
  jobs/aws/eks-distro/kubernetes-1-28-test-presubmits.yaml
  jobs/aws/eks-distro/kubernetes-1-29-test-presubmits.yaml
  templater/jobs/presubmit/eks-distro/kubernetes-1-X-test-presubmits.yaml
Labels: lgtm, approved, size/S
