Repository aws/eks-distro-prow-jobs, pull requests merged in 2024-08, with the labels that each got.

#622 Remove eks go postsubmits not related to the golang-debian image
  jobs/aws/eks-distro-build-tooling/golang-1-21-ARM64-PROD-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1-21-ARM64-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1-21-PROD-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1-21-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1-22-ARM64-PROD-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1-22-ARM64-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1-22-PROD-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1-22-postsubmits.yaml
  templater/jobs/postsubmit/eks-distro-build-tooling/golang-1-X-ARM64-PROD-postsubmits.yaml
  templater/jobs/postsubmit/eks-distro-build-tooling/golang-1-X-ARM64-postsubmits.yaml
  templater/jobs/postsubmit/eks-distro-build-tooling/golang-1-X-PROD-postsubmits.yaml
  templater/jobs/postsubmit/eks-distro-build-tooling/golang-1-X-postsubmits.yaml
Labels: lgtm, approved, size/XL

#626 increase ephemeral storage for k8s 1.29-1.31 test presubmits
  jobs/aws/eks-distro/kubernetes-1-29-test-presubmits.yaml
  jobs/aws/eks-distro/kubernetes-1-30-test-presubmits.yaml
  jobs/aws/eks-distro/kubernetes-1-31-test-presubmits.yaml
  templater/jobs/presubmit/eks-distro/kubernetes-1-X-test-presubmits.yaml
Labels: lgtm, approved, size/XS

#629 add go 1.23 prow jobs
  jobs/aws/eks-distro-build-tooling/eks-distro-base-presubmits-golang-1-23-al-2.yaml
  jobs/aws/eks-distro-build-tooling/eks-distro-base-presubmits-golang-1-23-al-2023.yaml
  jobs/aws/eks-distro-build-tooling/golang-1-23-PROD-images-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1-23-presubmits.yaml
  templater/jobs/utils/utils.go
Labels: lgtm, approved, size/L

#630 deprecate go 1.21
  jobs/aws/eks-distro-build-tooling/eks-distro-base-presubmits-golang-1-21-al-2.yaml
  jobs/aws/eks-distro-build-tooling/eks-distro-base-presubmits-golang-1-21-al-2023.yaml
  jobs/aws/eks-distro-build-tooling/golang-1-21-PROD-images-postsubmits.yaml
  jobs/aws/eks-distro-build-tooling/golang-1-21-presubmits.yaml
  templater/jobs/utils/utils.go
Labels: lgtm, approved, size/L
